version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""

    working_directory: ~/repo

    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: add settings.py
          command: |
            . venv/bin/activate
            invoke create-settings
      - run:
          name: make migrations
          command: |
            . venv/bin/activate
            python manage.py makemigrations
      - run:
          name: migrate db
          command: |
            . venv/bin/activate
            invoke migrate-db
      - run:
          name: load fixtures
          command: |
            . venv/bin/activate
            invoke load-fixtures
      - run:
          name: test flake8
          command: |
            . venv/bin/activate
            flake8 --config setup.cfg wger
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
